name: easy_load_more
description: Simple & easy to use flutter load more that supports ListView & SliverList.
version: 1.0.0
homepage: https://github.com/usefulteam/easy_load_more
issue_tracker: https://github.com/usefulteam/easy_load_more/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
