name: easy_load_more
description: Simple & easy to use flutter load more that supports ListView & SliverList.
version: 1.1.0
homepage: https://github.com/usefulteam/easy_load_more
issue_tracker: https://github.com/usefulteam/easy_load_more/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
